name: Serverless CI/CD

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: ["main"]

jobs:
  deploy:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    environment: docker
    steps:
      - uses: actions/checkout@main
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: daimox/lambda-runtime:phpoffice